{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "9e3b9644-b59d-47a5-a12a-52efb6d6e177",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: openpyxl in c:\\users\\hanss\\anaconda3\\lib\\site-packages (3.0.10)\n",
      "Requirement already satisfied: et_xmlfile in c:\\users\\hanss\\anaconda3\\lib\\site-packages (from openpyxl) (1.1.0)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: Ignoring invalid distribution ~ensorflow-intel (C:\\Users\\hanss\\anaconda3\\Lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution ~ensorflow-intel (C:\\Users\\hanss\\anaconda3\\Lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution ~ensorflow-intel (C:\\Users\\hanss\\anaconda3\\Lib\\site-packages)\n"
     ]
    }
   ],
   "source": [
    "!pip install openpyxl"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "7cddfa66-093f-4c8b-967a-62319b674109",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Template file 'Vessel_Charter_vs_Purchase_Template.xlsx' has been created successfully.\n",
      "Template file 'Vessel_Charter_vs_Purchase_Template.xlsx' has been created successfully.\n"
     ]
    }
   ],
   "source": [
    "import openpyxl\n",
    "from openpyxl import Workbook\n",
    "\n",
    "# Create a new workbook\n",
    "wb = Workbook()\n",
    "\n",
    "# ---------------------------\n",
    "# Sheet 1: Input Assumptions\n",
    "# ---------------------------\n",
    "sheet1 = wb.active\n",
    "sheet1.title = \"Input Assumptions\"\n",
    "sheet1.append([\"Assumption\", \"Time Charter Option\", \"Purchase Option\", \"Comments\"])\n",
    "sheet1.append([\"Vessel Name\", \"MV Whale Shark / MV Elbtraveller\", \"MV Whale Shark / MV Elbtraveller\", \"Specify which vessel you're evaluating\"])\n",
    "sheet1.append([\"Daily Charter Rate (USD)\", \"9000\", \"\", \"Example rate (adjust based on vessel specs)\"])\n",
    "sheet1.append([\"Operating Days (Year)\", \"360\", \"\", \"Adjust for planned maintenance/off-hire days\"])\n",
    "sheet1.append([\"Purchase Price (USD)\", \"\", \"30000000\", \"Example for geared cellular vessel\"])\n",
    "sheet1.append([\"Financing Interest Rate (%)\", \"\", \"5.5\", \"Annual interest rate for debt financing\"])\n",
    "sheet1.append([\"Loan Term (Years)\", \"\", \"7\", \"Duration of financing\"])\n",
    "sheet1.append([\"Annual Operating Cost (USD)\", \"\", \"1500000\", \"Includes crew, maintenance, bunkers, etc.\"])\n",
    "sheet1.append([\"Depreciation (Years)\", \"\", \"15\", \"Straight-line or your chosen method\"])\n",
    "sheet1.append([\"Residual Value (% of Purchase)\", \"\", \"20%\", \"Estimated percentage of purchase price at end\"])\n",
    "sheet1.append([\"Discount Rate (WACC, %)\", \"8\", \"8\", \"Used for DCF calculations\"])\n",
    "\n",
    "# -----------------------------------\n",
    "# Sheet 2: Time Charter Cash Flow Projection\n",
    "# -----------------------------------\n",
    "sheet2 = wb.create_sheet(title=\"Time Charter Cash Flow\")\n",
    "sheet2.append([\"Period\", \"Days\", \"Daily Charter Rate (USD)\", \"Total Charter Cost (USD)\"])\n",
    "sheet2.append([\"January\", \"30\", \"9000\", \"=30*9000\"])\n",
    "sheet2.append([\"February\", \"28\", \"9000\", \"=28*9000\"])\n",
    "sheet2.append([\"...\",\"...\",\"...\",\"...\"])\n",
    "sheet2.append([\"Total\", \"360\", \"\", \"=SUM(D2:D4)\"])  # Adjust cell references as needed\n",
    "\n",
    "# -----------------------------------\n",
    "# Sheet 3: Purchase Option Cash Flow Projection\n",
    "# -----------------------------------\n",
    "sheet3 = wb.create_sheet(title=\"Purchase Cash Flow\")\n",
    "sheet3.append([\"Year\", \"Initial Outlay/Investment (USD)\", \"Operating Cost (USD)\", \"Financing Cost (USD)\", \"Depreciation (USD)\", \"Net Cash Flow (USD)\", \"Notes\"])\n",
    "sheet3.append([\"0\", \"-30000000\", \"\", \"\", \"\", \"-30000000\", \"Initial purchase\"])\n",
    "sheet3.append([\"1\", \"\", \"-1500000\", \"=[Interest Expense]\", \"\", \"=Revenue? - (Operating + Financing)\", \"If revenue applies (e.g., additional cargo operations)\"])\n",
    "sheet3.append([\"2\", \"\", \"-1500000\", \"=[Interest Expense]\", \"\", \"...\", \"...\"])\n",
    "sheet3.append([\"Final Year\", \"\", \"-1500000\", \"=[Interest Expense]\", \"\", \"+[Residual Value]\", \"Include estimated resale value\"])\n",
    "\n",
    "# -----------------------------------\n",
    "# Sheet 4: DCF Analysis\n",
    "# -----------------------------------\n",
    "sheet4 = wb.create_sheet(title=\"DCF Analysis\")\n",
    "sheet4.append([\"Year/Period\", \"Cash Flow (Time Charter)\", \"Cash Flow (Purchase)\", \"Discount Factor (@8%)\", \"Present Value (Time Charter)\", \"Present Value (Purchase)\"])\n",
    "sheet4.append([\"0\", \"0 or initial cash outlay\", \"-30000000\", \"1.00\", \"0\", \"-30000000\"])\n",
    "sheet4.append([\"1\", \"[Aggregated Cash Flow]\", \"[Year 1 Cash Flow]\", \"=1/(1+0.08)^1\", \"=Cash Flow*DiscountFactor\", \"=Cash Flow*DiscountFactor\"])\n",
    "sheet4.append([\"2\", \"...\", \"...\", \"=1/(1+0.08)^2\", \"...\", \"...\"])\n",
    "sheet4.append([\"Total NPV\", \"=SUM(E2:E10)\", \"=SUM(F2:F10)\", \"\", \"\", \"\"])\n",
    "sheet4.append([\"IRR\", \"=IRR(range_of_cash_flows)\", \"=IRR(range_of_cash_flows)\", \"\", \"\", \"\"])\n",
    "\n",
    "# -----------------------------------\n",
    "# Sheet 5: Sensitivity Analysis\n",
    "# -----------------------------------\n",
    "sheet5 = wb.create_sheet(title=\"Sensitivity Analysis\")\n",
    "sheet5.append([\"Parameter\", \"Base Case\", \"Low Case\", \"High Case\", \"NPV Impact (Purchase)\", \"NPV Impact (Charter)\"])\n",
    "sheet5.append([\"Daily Charter Rate (USD)\", \"9000\", \"8000\", \"10000\", \"Calculate variation\", \"Calculate variation\"])\n",
    "sheet5.append([\"Purchase Price (USD)\", \"30000000\", \"28000000\", \"32000000\", \"Calculate variation\", \"\"])\n",
    "sheet5.append([\"Operating Costs (USD)\", \"1500000\", \"1300000\", \"1700000\", \"Calculate variation\", \"\"])\n",
    "sheet5.append([\"Discount Rate (%)\", \"8\", \"7\", \"9\", \"Calculate variation\", \"Calculate variation\"])\n",
    "\n",
    "# Save the workbook to a file\n",
    "wb.save(\"Vessel_Charter_vs_Purchase_Template.xlsx\")\n",
    "\n",
    "print(\"Template file 'Vessel_Charter_vs_Purchase_Template.xlsx' has been created successfully.\")\n",
    "import openpyxl\n",
    "from openpyxl import Workbook\n",
    "\n",
    "# Create a new workbook\n",
    "wb = Workbook()\n",
    "\n",
    "# ---------------------------\n",
    "# Sheet 1: Input Assumptions\n",
    "# ---------------------------\n",
    "sheet1 = wb.active\n",
    "sheet1.title = \"Input Assumptions\"\n",
    "sheet1.append([\"Assumption\", \"Time Charter Option\", \"Purchase Option\", \"Comments\"])\n",
    "sheet1.append([\"Vessel Name\", \"MV Whale Shark / MV Elbtraveller\", \"MV Whale Shark / MV Elbtraveller\", \"Specify which vessel you're evaluating\"])\n",
    "sheet1.append([\"Daily Charter Rate (USD)\", \"9000\", \"\", \"Example rate (adjust based on vessel specs)\"])\n",
    "sheet1.append([\"Operating Days (Year)\", \"360\", \"\", \"Adjust for planned maintenance/off-hire days\"])\n",
    "sheet1.append([\"Purchase Price (USD)\", \"\", \"30000000\", \"Example for geared cellular vessel\"])\n",
    "sheet1.append([\"Financing Interest Rate (%)\", \"\", \"5.5\", \"Annual interest rate for debt financing\"])\n",
    "sheet1.append([\"Loan Term (Years)\", \"\", \"7\", \"Duration of financing\"])\n",
    "sheet1.append([\"Annual Operating Cost (USD)\", \"\", \"1500000\", \"Includes crew, maintenance, bunkers, etc.\"])\n",
    "sheet1.append([\"Depreciation (Years)\", \"\", \"15\", \"Straight-line or your chosen method\"])\n",
    "sheet1.append([\"Residual Value (% of Purchase)\", \"\", \"20%\", \"Estimated percentage of purchase price at end\"])\n",
    "sheet1.append([\"Discount Rate (WACC, %)\", \"8\", \"8\", \"Used for DCF calculations\"])\n",
    "\n",
    "# -----------------------------------\n",
    "# Sheet 2: Time Charter Cash Flow Projection\n",
    "# -----------------------------------\n",
    "sheet2 = wb.create_sheet(title=\"Time Charter Cash Flow\")\n",
    "sheet2.append([\"Period\", \"Days\", \"Daily Charter Rate (USD)\", \"Total Charter Cost (USD)\"])\n",
    "sheet2.append([\"January\", \"30\", \"9000\", \"=30*9000\"])\n",
    "sheet2.append([\"February\", \"28\", \"9000\", \"=28*9000\"])\n",
    "sheet2.append([\"...\",\"...\",\"...\",\"...\"])\n",
    "sheet2.append([\"Total\", \"360\", \"\", \"=SUM(D2:D4)\"])  # Adjust cell references as needed\n",
    "\n",
    "# -----------------------------------\n",
    "# Sheet 3: Purchase Option Cash Flow Projection\n",
    "# -----------------------------------\n",
    "sheet3 = wb.create_sheet(title=\"Purchase Cash Flow\")\n",
    "sheet3.append([\"Year\", \"Initial Outlay/Investment (USD)\", \"Operating Cost (USD)\", \"Financing Cost (USD)\", \"Depreciation (USD)\", \"Net Cash Flow (USD)\", \"Notes\"])\n",
    "sheet3.append([\"0\", \"-30000000\", \"\", \"\", \"\", \"-30000000\", \"Initial purchase\"])\n",
    "sheet3.append([\"1\", \"\", \"-1500000\", \"=[Interest Expense]\", \"\", \"=Revenue? - (Operating + Financing)\", \"If revenue applies (e.g., additional cargo operations)\"])\n",
    "sheet3.append([\"2\", \"\", \"-1500000\", \"=[Interest Expense]\", \"\", \"...\", \"...\"])\n",
    "sheet3.append([\"Final Year\", \"\", \"-1500000\", \"=[Interest Expense]\", \"\", \"+[Residual Value]\", \"Include estimated resale value\"])\n",
    "\n",
    "# -----------------------------------\n",
    "# Sheet 4: DCF Analysis\n",
    "# -----------------------------------\n",
    "sheet4 = wb.create_sheet(title=\"DCF Analysis\")\n",
    "sheet4.append([\"Year/Period\", \"Cash Flow (Time Charter)\", \"Cash Flow (Purchase)\", \"Discount Factor (@8%)\", \"Present Value (Time Charter)\", \"Present Value (Purchase)\"])\n",
    "sheet4.append([\"0\", \"0 or initial cash outlay\", \"-30000000\", \"1.00\", \"0\", \"-30000000\"])\n",
    "sheet4.append([\"1\", \"[Aggregated Cash Flow]\", \"[Year 1 Cash Flow]\", \"=1/(1+0.08)^1\", \"=Cash Flow*DiscountFactor\", \"=Cash Flow*DiscountFactor\"])\n",
    "sheet4.append([\"2\", \"...\", \"...\", \"=1/(1+0.08)^2\", \"...\", \"...\"])\n",
    "sheet4.append([\"Total NPV\", \"=SUM(E2:E10)\", \"=SUM(F2:F10)\", \"\", \"\", \"\"])\n",
    "sheet4.append([\"IRR\", \"=IRR(range_of_cash_flows)\", \"=IRR(range_of_cash_flows)\", \"\", \"\", \"\"])\n",
    "\n",
    "# -----------------------------------\n",
    "# Sheet 5: Sensitivity Analysis\n",
    "# -----------------------------------\n",
    "sheet5 = wb.create_sheet(title=\"Sensitivity Analysis\")\n",
    "sheet5.append([\"Parameter\", \"Base Case\", \"Low Case\", \"High Case\", \"NPV Impact (Purchase)\", \"NPV Impact (Charter)\"])\n",
    "sheet5.append([\"Daily Charter Rate (USD)\", \"9000\", \"8000\", \"10000\", \"Calculate variation\", \"Calculate variation\"])\n",
    "sheet5.append([\"Purchase Price (USD)\", \"30000000\", \"28000000\", \"32000000\", \"Calculate variation\", \"\"])\n",
    "sheet5.append([\"Operating Costs (USD)\", \"1500000\", \"1300000\", \"1700000\", \"Calculate variation\", \"\"])\n",
    "sheet5.append([\"Discount Rate (%)\", \"8\", \"7\", \"9\", \"Calculate variation\", \"Calculate variation\"])\n",
    "\n",
    "# Save the workbook to a file\n",
    "wb.save(\"Vessel_Charter_vs_Purchase_Template.xlsx\")\n",
    "\n",
    "print(\"Template file 'Vessel_Charter_vs_Purchase_Template.xlsx' has been created successfully.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ac206239-07c9-444f-9c66-e9c45411a921",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
